### ISSUE TITLE
Made an AUR package

### ISSUE THREAD

**Issue by Stetsed** [lhl/batterylog#4]
Hey,

So I found this tool useful and got it from somebody inside the framework discord. I have made an AUR package for it [here](https://aur.archlinux.org/packages/batterylog-git) incase anybody wants to use it on arch and install it via the package manager(or well AUR helper ig)

Sorry if this isn't the right place to say I have made an AUR package you can close this issue if you want.

**Comment by lhl** [comment]
hey no worries, appreciated. i'll put info on the package in the readme. glad you found it useful, have been meaning to revisit the code, but it does what i needed, maybe when my ryzen motherboard arrives i'll take a look again. :)
